# Generated by Django 5.2.8 on 2025-12-02 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwarehouse',
            name='legacy_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('manager', 'Manager'), ('operator', 'Operator'), ('viewer', 'Viewer')], help_text="Legacy role field. Use 'role' FK instead.", max_length=20),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_system_role', models.BooleanField(default=False, help_text='System roles (admin, manager, etc.) cannot be deleted.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='accounts.company')),
                ('permissions', models.ManyToManyField(blank=True, help_text='Django permissions assigned to this role.', related_name='roles', to='auth.permission')),
            ],
            options={
                'ordering': ('company__name', 'name'),
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='userwarehouse',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Custom role with specific permissions. Takes precedence over legacy_role.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_warehouse_assignments', to='accounts.role'),
        ),
    ]
