# Generated by Django 5.2.8 on 2025-12-05 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userwarehouse_legacy_role_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('manage_warehouse', 'Can manage warehouse settings and assignments')]},
        ),
    ]
