# Generated by Django 5.2.8 on 2025-12-02 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inboundorder',
            options={'ordering': ('-created_at',), 'permissions': [('view_orders', 'Can view orders'), ('manage_orders', 'Can create and manage orders'), ('pick_orders', 'Can pick orders'), ('putaway', 'Can perform putaway')]},
        ),
    ]
