# Generated by Django 5.2.8 on 2025-12-01 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Short unique code for this warehouse (e.g. WH-01, KHI-01).', max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('time_zone', models.CharField(blank=True, max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('type', models.CharField(choices=[('main', 'Main DC'), ('store', 'Store / Outlet'), ('3pl', '3PL / External'), ('other', 'Other')], default='main', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_negative_stock', models.BooleanField(default=False)),
                ('uses_bins', models.BooleanField(default=True, help_text='If false, you might store stock at warehouse level only.')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='accounts.company')),
            ],
            options={
                'ordering': ('company__name', 'code'),
                'unique_together': {('company', 'code')},
            },
        ),
    ]
