# Generated by Django 5.2.8 on 2025-12-02 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_pickable', models.BooleanField(default=True)),
                ('is_putaway_allowed', models.BooleanField(default=True)),
                ('is_countable', models.BooleanField(default=True)),
                ('temperature_zone', models.CharField(blank=True, help_text='e.g. ambient, chiller, freezer.', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_types', to='accounts.company')),
            ],
            options={
                'ordering': ('company__name', 'code'),
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='accounts.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='masterdata.productcategory')),
            ],
            options={
                'ordering': ('company__name', 'name'),
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('discontinued', 'Discontinued')], default='active', max_length=20)),
                ('default_uom', models.CharField(help_text='Primary UOM code (e.g. EA)', max_length=20)),
                ('storage_uom', models.CharField(blank=True, help_text='Optional alternate UOM used in storage.', max_length=20)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('volume_cbm', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('track_batch', models.BooleanField(default=False)),
                ('track_serial', models.BooleanField(default=False)),
                ('hazardous', models.BooleanField(default=False)),
                ('requires_lot_expiry', models.BooleanField(default=False)),
                ('storage_requirements', models.TextField(blank=True, help_text='Special instructions (temperature, stacking rules, etc.).')),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.company')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='masterdata.productcategory')),
            ],
            options={
                'ordering': ('company__name', 'sku'),
                'unique_together': {('company', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='masterdata.warehouse')),
            ],
            options={
                'ordering': ('warehouse__code', 'code'),
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('levels', models.PositiveIntegerField(default=1)),
                ('positions_per_level', models.PositiveIntegerField(default=1)),
                ('max_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_volume_cbm', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='masterdata.warehouse')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='masterdata.section')),
            ],
            options={
                'ordering': ('section__warehouse__code', 'section__code', 'code'),
                'unique_together': {('section', 'code')},
            },
        ),
        migrations.CreateModel(
            name='WarehouseZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, help_text='For UI highlighting (hex code).', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='masterdata.warehouse')),
            ],
            options={
                'ordering': ('warehouse__code', 'name'),
                'unique_together': {('warehouse', 'name')},
            },
        ),
        migrations.AddField(
            model_name='section',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='masterdata.warehousezone'),
        ),
        migrations.CreateModel(
            name='ProductBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, help_text="e.g. 'EAN13', 'Case barcode'.", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='masterdata.product')),
            ],
            options={
                'unique_together': {('product', 'barcode')},
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Human readable code (e.g. A1-R01-BIN05).', max_length=100)),
                ('barcode', models.CharField(blank=True, help_text='Optional barcode / QR for scanning.', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('pick_sequence', models.PositiveIntegerField(default=0, help_text='Used to optimize picking routes (lower = earlier).')),
                ('length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='masterdata.warehouse')),
                ('location_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='masterdata.locationtype')),
                ('rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='masterdata.rack')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='masterdata.section')),
            ],
            options={
                'ordering': ('warehouse__code', 'code'),
                'unique_together': {('warehouse', 'code')},
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('base_unit', models.CharField(help_text='Reference unit code used for conversions (e.g. EA).', max_length=20)),
                ('conversion_factor', models.DecimalField(decimal_places=5, help_text='How many base units make one of this unit.', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units_of_measure', to='accounts.company')),
            ],
            options={
                'ordering': ('company__name', 'name'),
                'unique_together': {('company', 'abbreviation')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('warehouse', 'code')},
        ),
    ]
