# Generated by Django 5.2.8 on 2025-12-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_carrier_customer_reasoncode_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='code',
            field=models.CharField(help_text='Short unique code for this warehouse (e.g. WH-01, KHI-01). Unique per company.', max_length=50),
        ),
    ]
