# Generated by Django 5.2.8 on 2025-12-01 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('masterdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('inventory_item', 'Inventory item')], default='inventory_item', max_length=50)),
                ('name', models.CharField(help_text="Internal key, e.g. 'color' or 'qc_status'.", max_length=100)),
                ('label', models.CharField(help_text="User-facing label, e.g. 'Color' or 'QC Status'.", max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_definitions', to='accounts.company')),
            ],
            options={
                'ordering': ('company__name', 'scope', 'order', 'name'),
                'unique_together': {('company', 'scope', 'name')},
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku', models.CharField(max_length=100)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('location_code', models.CharField(blank=True, help_text='Temporary location identifier until Location model is defined.', max_length=100)),
                ('batch', models.CharField(blank=True, help_text='Batch / lot number if you need batch tracking.', max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('reserved_quantity', models.DecimalField(decimal_places=3, default=0, help_text='Qty reserved for orders.', max_digits=18)),
                ('is_locked', models.BooleanField(default=False, help_text='If true, stock cannot be moved (e.g. under investigation).')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='accounts.company')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='masterdata.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItemCustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_values', to='inventory.customfielddefinition')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='inventory.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku', models.CharField(max_length=100)),
                ('location_from', models.CharField(blank=True, max_length=100)),
                ('location_to', models.CharField(blank=True, max_length=100)),
                ('batch', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('movement_type', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('move', 'Move'), ('adjustment', 'Adjustment')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('reference', models.CharField(blank=True, help_text='External reference (order, PO, task id, etc.).', max_length=100)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_movements', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='masterdata.warehouse')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku', models.CharField(max_length=100)),
                ('location_code', models.CharField(blank=True, max_length=100)),
                ('reason', models.CharField(choices=[('damage', 'Damage'), ('loss', 'Loss / Missing'), ('count', 'Stock count variance'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('quantity_difference', models.DecimalField(decimal_places=3, help_text='Positive = increase stock, negative = decrease.', max_digits=18)),
                ('reference', models.CharField(blank=True, help_text='Optional link to count session / external document.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='masterdata.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='StockCountSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('count_type', models.CharField(choices=[('cycle', 'Cycle count'), ('full', 'Full count')], default='cycle', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='draft', max_length=20)),
                ('scope_description', models.TextField(blank=True, help_text='Free-text description of what is being counted.')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_count_sessions', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_count_sessions', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_count_sessions', to='masterdata.warehouse')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StockCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku', models.CharField(max_length=100)),
                ('location_code', models.CharField(blank=True, max_length=100)),
                ('system_quantity', models.DecimalField(decimal_places=3, help_text='Quantity according to system at the time of counting.', max_digits=18)),
                ('counted_quantity', models.DecimalField(decimal_places=3, help_text='Quantity physically counted.', max_digits=18)),
                ('difference', models.DecimalField(decimal_places=3, help_text='counted - system', max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_count_lines', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockcountsession')),
            ],
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['company', 'warehouse', 'product_sku', 'location_code'], name='inventory_i_company_2694e7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitemcustomfieldvalue',
            unique_together={('item', 'field')},
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['company', 'warehouse', 'product_sku', 'movement_type', 'created_at'], name='inventory_i_company_ad67d9_idx'),
        ),
        migrations.AddIndex(
            model_name='stockcountline',
            index=models.Index(fields=['session', 'product_sku', 'location_code'], name='inventory_s_session_6ed6b2_idx'),
        ),
    ]
