# Generated by Django 5.2.8 on 2025-12-02 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('inventory', '0001_initial'),
        ('masterdata', '0002_locationtype_productcategory_product_section_rack_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inventoryitem',
            name='inventory_i_company_2694e7_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorymovement',
            name='inventory_i_company_ad67d9_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockcountline',
            name='inventory_s_session_6ed6b2_idx',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='location_code',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='product_sku',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='product_sku',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='location_code',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='product_sku',
        ),
        migrations.RemoveField(
            model_name='stockcountline',
            name='location_code',
        ),
        migrations.RemoveField(
            model_name='stockcountline',
            name='product_sku',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='masterdata.location'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='masterdata.product'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='masterdata.product'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments', to='masterdata.location'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='masterdata.product'),
        ),
        migrations.AddField(
            model_name='stockcountline',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_count_lines', to='masterdata.location'),
        ),
        migrations.AddField(
            model_name='stockcountline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_count_lines', to='masterdata.product'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='location_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_source', to='masterdata.location'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='location_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_destination', to='masterdata.location'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['company', 'warehouse', 'product', 'location'], name='inventory_i_company_e5da19_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['company', 'warehouse', 'product', 'movement_type', 'created_at'], name='inventory_i_company_d13fd8_idx'),
        ),
        migrations.AddIndex(
            model_name='stockcountline',
            index=models.Index(fields=['session', 'product', 'location'], name='inventory_s_session_d11e62_idx'),
        ),
    ]
