# Generated by Django 5.2.8 on 2025-12-02 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_inventoryitem_inventory_i_company_2694e7_idx_and_more'),
        ('masterdata', '0003_carrier_customer_reasoncode_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfielddefinition',
            name='scope',
            field=models.CharField(choices=[('product', 'Product'), ('inventory_item', 'Inventory item')], default='inventory_item', max_length=50),
        ),
        migrations.CreateModel(
            name='ProductCustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_values', to='inventory.customfielddefinition')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='masterdata.product')),
            ],
            options={
                'unique_together': {('product', 'field')},
            },
        ),
    ]
