# Generated by Django 5.2.8 on 2025-12-02 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_customfielddefinition_scope_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'permissions': [('view_inventory', 'Can view inventory'), ('manage_inventory', 'Can manage inventory (adjustments, counts)')]},
        ),
    ]
